task_type: pretraining
output_dir: output/pretrain_eegmamba
device: cuda
epochs: 100
clip_grad: 1.0
metric_key: loss
val_freq_split: 5

enable_wandb: true
project: "eeg-knowledge-engine"
entity: "bci-foundation-model"

dataset:
  name: TUEG
  dataset_dir: /vePFS-0x0d/pretrain-clip/output_tuh_full_pipeline/merged_final_dataset
  seed: 42
  batch_size: 128
  num_workers: 8
  cache_path: output/pretrain_eegmamba/dataset_index.json
  feature_path: '/vePFS-0x0d/pretrain-clip/feature_analysis/features_final_zscore.csv'

model:
  name: eegmamba
  use_pretrained: false
  in_dim: 200
  d_model: 200
  dim_feedforward: 800
  seq_len: 30 # Will be overridden by script
  n_layer: 12
  nhead: 8
  dropout: 0.1
  
  pretrain_tasks: ['reconstruction']
  
  feature_dim: 62
  feature_token_type: 'cross_attn'
  feature_token_strategy: 'single'
  feature_group_count: 5

loss:
  name: mse
  feature_loss_weight: 1.0
  
optimizer:
  name: AdamW
  lr: 0.001
  weight_decay: 0.05

scheduler:
  name: CosineAnnealingLR
  T_max: 100
  eta_min: 1.0e-6
